config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/about'
  get 'static_pages/help'

  devise_for :users
  resources :users
  resources :documents

end

app/models/document.rb
class Document < ActiveRecord::Base
	has_attached_file :file

	belongs_to :user, :foreign_key => :owner_id

	do_not_validate_attachment_file_type :file
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :documents, :foreign_key => :owner_id, class_name: Document
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
	before_action :authenticate_user!

	def index
		@documents = Document.all
		#@documents = current_user.documents
	end

	def new
		@document = Document.new
	end

	def create
		@document = Document.new(document_params)
		@document.user = current_user
		if @document.save
			redirect_to @document
		else
			render 'new'
		end
	end

	def show
		@document = Document.find(params[:id])
	end

	def search
	end

	def destroy
		@document = Document.find(params[:id])
		@document.destroy
		redirect_to documents_path
	end

	private
		def document_params
			params.require(:document).permit(:title, :file, :owner_id)
		end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def about
	end

	def help
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/documents/index.html.erb
<h2>My documents</h2>

<div class="container">
	<div class="col-md-12">
		<%= button_to "Upload document", new_document_path, :class => "btn btn-default", :method => "get" %> <br />
		
		<table class="table table-bordered">
			<tr>
				<th>Name</th>
				<th>File</th>
				<th>Owner</th>
			</tr>
			<% @documents.each do |document| %>
				<tr>
					<td><%= link_to document.title, document %></td>
					<td><%= document.file %></td>
					<td><%= document.user.email %></td>
				</tr>
			<% end %>
		</table>
	</div>
</div>

app/views/documents/new.html.erb
<%= form_for @document do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %> <br />
	<%= f.label :file %>
	<%=	f.file_field :file %>
	<!--<%= f.select :owner_id, User.all.map{ |user| [user.email, user.id] } %>-->
  <br>
  <%= f.submit "Upload" %>
<% end %>

app/views/documents/show.html.erb
<h2><%= @document.title %></h2>
<div class="container">
Owner: <%= @document.user.email %> <br />
<%= link_to "Delete", @document, :method => :delete %>
<%= link_to "Download file", @document.file.url(:original, false) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SEProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- header is here -->
	<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Project name", root_path, :class => "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", static_pages_about_path %></li>
          <li><%= link_to "Help", static_pages_help_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Documents", documents_path %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav pull-right">
        	<% if user_signed_in? %>
        		<li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
          <% else %>
          	<li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>

      </div>
    </div>
  </nav>
  <div class="container">
		<%= yield %>
  </div>
  <!-- footer is here -->
</body>
</html>

app/views/static_pages/about.html.erb
<h1>About</h1>

app/views/static_pages/help.html.erb
<h1>Help</h1>

app/views/static_pages/home.html.erb
<h1>Homepage</h1>